apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://10.166.64.12:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.x
      cacheLevel: "High"
      incrementalQueryOverlapWindow: 10m
    secureJsonData:
      # Se houver autenticação, colocar aqui
      # basicAuthPassword: password
    uid: prometheus-prod