{
 "title": "Veeam One",
 "tags": [
  "veeam",
  "backup",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Visão Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/01/onpremvbr-5.png\"></img>"
   }
  },
  {
   "title": "Sobre",
   "type": "table",
   "description": "Repositório de coleta de dados do Veeam One",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "targets": [
    { "expr": "veeam_one_info", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(veeam_job_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sucesso",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_job_info{status=\"Success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executando",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_job_info{status=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_job_info{status=\"Warning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Falhados",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_job_info{status=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jobs por Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Jobs em Execução",
   "type": "table",
   "description": "List of running jobs with their last run time and duration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "veeam_job_info{status=\"Success\"}"
    }
   ]
  },
  {
   "title": "Jobs em Execução",
   "type": "table",
   "description": "List of running jobs with their last run time and duration",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "veeam_job_info{status=\"Running\"}"
    }
   ]
  },
  {
   "title": "Jobs com Warnings",
   "type": "table",
   "description": "List of jobs with warnings with their last run time and duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "veeam_job_info{status=\"Warning\"}"
    },
    {
     "expr": "veeam_job_last_run_duration_seconds{status=\"Warning\"}"
    }
   ]
  },
  {
   "title": "Jobs com Falhas",
   "type": "table",
   "description": "Lista de jobs com falha contendo horário da última execução e duração",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "veeam_job_info{status=\"Failed\"}"
    }
   ]
  },
  { "title": "Estatísticas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Duração dos Jobs",
   "type": "barchart",
   "description": "Top 5 jobs with longest duration in last run",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "veeam_job_last_run_duration_seconds / 3600",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Média de Duração Por Job",
   "type": "barchart",
   "description": "Average duration of jobs in seconds",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(veeam_job_avg_duration_seconds)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Jobs mais longos",
   "type": "barchart",
   "description": "Top 5 jobs with longest duration in last run",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, veeam_job_last_run_duration_seconds)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Maiores Jobs por Volume de Dados",
   "type": "gauge",
   "description": "Top 5 jobs with most data transferred in last run",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, veeam_job_last_transferred_data_bytes)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}